import "./globals.css";
import { Session } from "next-auth";
import { headers } from "next/headers";
import AuthContext from "../lib/AuthContext";
import Header from "../components/Header";
import { NextAuthProvider } from "./providers";
import UploadModal from "@/components/UploadModal";
import { RecoilContext } from "@/lib/RecoilContext";
import PostViewModal from "@/components/PostViewModal";

export const metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <RecoilContext>
            <Header />
            {/* Header */}
            {/* Feed section */}
            {children}
            {/* Modal */}
            <UploadModal />
            <PostViewModal />
          </RecoilContext>
        </NextAuthProvider>
      </body>
    </html>
  );
}
